- args:
    relationship: user
    table:
      name: refresh_tokens
      schema: public
  type: drop_relationship
- args:
    relationship: user_roles
    table:
      name: roles
      schema: public
  type: drop_relationship
- args:
    relationship: users
    table:
      name: roles
      schema: public
  type: drop_relationship
- args:
    relationship: roleByRole
    table:
      name: user_roles
      schema: public
  type: drop_relationship
- args:
    relationship: user
    table:
      name: user_roles
      schema: public
  type: drop_relationship
- args:
    relationship: role
    table:
      name: users
      schema: public
  type: drop_relationship
- args:
    relationship: refresh_tokens
    table:
      name: users
      schema: public
  type: drop_relationship
- args:
    relationship: user_roles
    table:
      name: users
      schema: public
  type: drop_relationship
