- args:
    relationship: user
    table:
      name: user_session
      schema: public
  type: drop_relationship
- args:
    relationship: sessions
    table:
      name: user
      schema: public
  type: drop_relationship